name: 'sus-map'
services:
  app:
    image: 'node:20-alpine'
    ports:
      - '3000:3000'
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
    tty: true
    command: sh -c "npm install && npm run dev"
